compute_environment: LOCAL_MACHINE

# Multi-GPU setup (8 GPUs with standard DDP - no DeepSpeed/ZeRO)
# gpu_ids: "0,1,2,3,4,5,6,7"
# num_processes: 8  # should be the same as the number of GPUs

# Single-GPU setup (uncomment to use just 1 GPU)
# gpu_ids: "0"
# num_processes: 1

# Using 7 available A100 GPUs (40GB each = 280GB total)
gpu_ids: "2,3,4,5,6,7"
num_processes: 6

debug: false
# DeepSpeed ZeRO-3 with CPU offload for maximum memory efficiency
deepspeed_config:
  deepspeed_config_file: /scratch/tkim462/vision/finetune/configs/zero3_offload.yaml
  zero3_init_flag: true
distributed_type: DEEPSPEED  # Using DeepSpeed ZeRO-3 with CPU offload
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false